<?xml version="1.0" encoding="utf-8"?><Database Name="Mirim2018" Class="Mus_memberDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=14.63.199.209,5433;Initial Catalog=Mirim2018;Persist Security Info=True;User ID=mirim2018" SettingsObjectName="muscle.Properties.Settings" SettingsPropertyName="Mirim2018ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Mus_member" Member="Mus_member">
    <Type Name="Mus_member">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[level]" Member="level" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="dumbbell" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>